name: my_wallet
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.2.2
  mocktail: ^1.0.4
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  intl: ^0.20.2
  flutter_multi_formatter: ^2.13.10
  sqflite: ^2.4.2
  path_provider: ^2.1.5

  user_session_manager:
    git:
      url: https://github.com/CJGalvis/user_session_manager.git

  my_wallet_core:
    path: ../my_wallet_core

  my_wallet_auth:
    path: ../my_wallet_auth

  my_wallet_home:
    path: ../my_wallet_home

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/locale/en/
    - assets/locale/es/
    - assets/icons/
    - assets/illustrations/